# Generated by Django 3.1.6 on 2021-03-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='boy',
            new_name='body',
        ),
    ]
