# Generated by Django 3.1.6 on 2021-03-21 16:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_auto_20210321_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Post',
        ),
    ]
